import type { LabValue, ReportMeta } from "../types/value";

export const MOCK_REPORT_META: ReportMeta = {
  label: "Blood panel",
  date: "12 Sep 2026",
};

// Illustrative sample data (matches the design's 11-value / 2-flag / 3-borderline / 6-normal spread).
// Used when the backend runs with MOCK_AI=true or is unreachable, so the UI is always demoable.
export const MOCK_VALUES: LabValue[] = [
  {
    key: "hb",
    name: "Hemoglobin",
    value: "10.2",
    unit: "g/dL",
    status: "low",
    ref: "12.0 – 15.5 g/dL",
    marker: 16,
    bandA: 40,
    bandB: 78,
    plain: "Your hemoglobin is low",
    meaning:
      "Hemoglobin carries oxygen from your lungs to the rest of your body. Yours is below the typical range, which can leave you feeling tired or short of breath and usually points to iron levels worth checking.",
    helps: [
      "Add iron-rich foods — red meat, spinach, lentils — alongside vitamin C to help absorption",
      "Ask your doctor about an iron panel to find the cause before starting supplements",
      "Flag any heavy periods, fatigue or dizziness at your next visit",
    ],
    category: "RBC Parameters",
  },
  {
    key: "ldl",
    name: "LDL Cholesterol",
    value: "168",
    unit: "mg/dL",
    status: "high",
    ref: "Below 100 mg/dL",
    marker: 86,
    bandA: 0,
    bandB: 55,
    plain: "Your LDL cholesterol is high",
    meaning:
      "LDL is the cholesterol that can build up in your artery walls over time. Yours is well above the target, which raises long-term risk for heart disease if it stays there.",
    helps: [
      "Cut back on saturated fat — fried food, fatty cuts of meat, full-fat dairy",
      "Add soluble fibre — oats, beans, apples — which helps lower LDL directly",
      "Get moving most days; even brisk walking measurably improves LDL over months",
    ],
    category: "Lipid Panel",
  },
  {
    key: "hba1c",
    name: "HbA1c",
    value: "5.9",
    unit: "%",
    status: "borderline",
    ref: "Below 5.7 %",
    marker: 68,
    bandA: 0,
    bandB: 62,
    plain: "Your HbA1c is borderline",
    meaning:
      "HbA1c reflects your average blood sugar over the last 2–3 months. Yours sits just above the normal range, in the range doctors call prediabetes — it's a signal to act now, not a diagnosis.",
    helps: [
      "Cut back on refined carbs and sugary drinks — they move this number the most",
      "Add a 10–15 minute walk after meals to blunt blood sugar spikes",
      "Recheck in 3–6 months to see the trend, not just one number",
    ],
    category: "Metabolic Panel",
  },
  {
    key: "vitd",
    name: "Vitamin D",
    value: "28",
    unit: "ng/mL",
    status: "borderline",
    ref: "30 – 100 ng/mL",
    marker: 22,
    bandA: 27,
    bandB: 88,
    plain: "Your vitamin D is borderline low",
    meaning:
      "Vitamin D supports bone health, muscle function and immune response. Yours is just under the normal range — common if you get limited sun exposure — and is easy to correct.",
    helps: [
      "Get 10–15 minutes of midday sun on your arms/face a few times a week if you can",
      "Add vitamin D sources — fatty fish, egg yolks, fortified milk",
      "Ask your doctor whether a daily supplement makes sense for you",
    ],
    category: "Vitamins",
  },
  {
    key: "glucose",
    name: "Fasting Glucose",
    value: "92",
    unit: "mg/dL",
    status: "normal",
    ref: "70 – 99 mg/dL",
    marker: 45,
    bandA: 20,
    bandB: 80,
    plain: "Your fasting glucose is in range",
    meaning:
      "This measures blood sugar after a period without eating. Yours is comfortably within the normal range, with no signs of insulin resistance.",
    helps: [
      "Keep the habits that got you here — regular meals, regular activity",
      "Worth rechecking yearly, especially alongside HbA1c",
    ],
    category: "Metabolic Panel",
  },
  {
    key: "tsh",
    name: "TSH",
    value: "4.3",
    unit: "mIU/L",
    status: "borderline",
    ref: "0.4 – 4.0 mIU/L",
    marker: 78,
    bandA: 15,
    bandB: 72,
    plain: "Your TSH is borderline high",
    meaning:
      "TSH signals your thyroid to produce hormone — a slightly high reading can mean your thyroid is working a little harder than usual to keep hormone levels normal.",
    helps: [
      "Mention any fatigue, weight change or cold sensitivity to your doctor",
      "A repeat test in a few months is the usual next step, not immediate treatment",
    ],
    category: "Endocrine Panel",
  },
  {
    key: "creatinine",
    name: "Creatinine",
    value: "0.9",
    unit: "mg/dL",
    status: "normal",
    ref: "0.6 – 1.3 mg/dL",
    marker: 43,
    bandA: 20,
    bandB: 80,
    plain: "Your creatinine is in range",
    meaning:
      "Creatinine is a waste product filtered by your kidneys. Yours is normal, suggesting your kidneys are clearing it efficiently.",
    helps: ["Stay well hydrated day to day", "No action needed — keep this as a baseline for future checkups"],
    category: "Kidney Panel",
  },
  {
    key: "wbc",
    name: "White Blood Cell Count",
    value: "6.8",
    unit: "x10³/µL",
    status: "normal",
    ref: "4.0 – 11.0 x10³/µL",
    marker: 40,
    bandA: 15,
    bandB: 85,
    plain: "Your white cell count is in range",
    meaning: "White blood cells fight infection. Your count is normal, with no sign of active infection or immune stress.",
    helps: ["No action needed here"],
    category: "Haematology",
  },
  {
    key: "platelets",
    name: "Platelets",
    value: "265",
    unit: "x10³/µL",
    status: "normal",
    ref: "150 – 400 x10³/µL",
    marker: 46,
    bandA: 15,
    bandB: 85,
    plain: "Your platelets are in range",
    meaning: "Platelets help your blood clot. Yours are within the normal range, so clotting function looks typical.",
    helps: ["No action needed here"],
    category: "Haematology",
  },
  {
    key: "alt",
    name: "ALT",
    value: "28",
    unit: "U/L",
    status: "normal",
    ref: "7 – 56 U/L",
    marker: 43,
    bandA: 12,
    bandB: 88,
    plain: "Your ALT is in range",
    meaning: "ALT is a liver enzyme. Yours is normal, with no sign of liver stress or inflammation.",
    helps: ["No action needed here"],
    category: "Liver Panel",
  },
  {
    key: "hdl",
    name: "HDL Cholesterol",
    value: "52",
    unit: "mg/dL",
    status: "normal",
    ref: "Above 40 mg/dL",
    marker: 62,
    bandA: 45,
    bandB: 100,
    plain: "Your HDL cholesterol is in range",
    meaning: "HDL is the “good” cholesterol that helps clear LDL from your arteries. Yours is healthy and working in your favour.",
    helps: ["Keep up regular activity — it's one of the best ways to raise HDL further"],
    category: "Lipid Panel",
  },
];

export const WALKTHROUGH_KEYS = ["hb", "ldl", "hba1c", "vitd"];
